providers:
  messagebird:
    access_key: 'live_qKwVZ02ULV70GqabBYxLU8d5r'
  nexmo:
    api_key: '18e0a6e9'
    api_secret: 'ea44c2d9'

receivers:
  - name: 'team-sms'
    provider: 'messagebird'
    to:
      - '+31612345678'
    from: 'Sachet'
    text: 'Something was sent from the Prometheus Alertmanager!'

